# Generated by Django 5.0.7 on 2024-08-03 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertrix', '0002_alter_directmessage_with_user_widget'),
        ('matrixappservice', '0002_event_room_applicationserviceregistration_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
           model_name='company',
           name='handler',
        ),
        migrations.RemoveField(
           model_name='handler',
           name='application_service',
        ),
        migrations.RemoveField(
            model_name='handler',
            name='users',
        ),
        migrations.DeleteModel(
            name='Handler',
        ),
    ]
