# Generated by Django 5.0.7 on 2024-08-03 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertrix', '0003_remove_handler'),
        ('matrixappservice', '0002_event_room_applicationserviceregistration_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directmessage',
            name='with_user',
        ),
        migrations.RemoveField(
            model_name='matrixroom',
            name='responsible_user',
        ),
        migrations.AlterField(
            model_name='widget',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrixappservice.room'),
        ),
        migrations.CreateModel(
            name='MainUserKey',
            fields=[
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='matrixappservice.applicationserviceregistration')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matrixappservice.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='DirectMessage',
        ),
        migrations.DeleteModel(
            name='MatrixRoom',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
