# Generated by Django 5.0.7 on 2024-09-01 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alertrix', '0007_unit'),
        ('matrixappservice', '0007_alter_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('matrixappservice.room',),
        ),
    ]
