# Generated by Django 5.1.1 on 2024-09-14 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alertrix', '0008_directmessage'),
        ('matrixappservice', '0008_user_prevent_automated_responses'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertChannel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('matrixappservice.room',),
        ),
    ]
