# Generated by Django 5.0.6 on 2024-05-18 09:56

import alertrix.accounts.utils
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationToken',
            fields=[
                ('token', models.TextField(default=alertrix.accounts.utils.get_token, primary_key=True, serialize=False)),
                ('valid_for_matrix_id', models.TextField()),
                ('requested_tms', models.DateTimeField(auto_now_add=True)),
                ('valid_for_duration', models.DurationField(default=datetime.timedelta(seconds=300))),
            ],
        ),
    ]
